version:  '3'

services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - '3000:80'
    restart: always
    
  juiceshop:
    image: bkimminich/juice-shop 
    ports:
      - '3001:3000'
    restart: always
    
  vampi:
    image: erev0s/vampi
    ports:
      - '3002:5000'
    restart: always
