version:  '1'

services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - '3000:80'
  juiceshop:
    image: bkimminich/juice-shop 
    ports:
      - '3001:3000'

  vampi:
    image: erev0s/vampi
    ports:
      - '3002:5000'
